//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.Recipe.File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.Recipe.File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align: center;&quot;&gt;Simple File Configurator&lt;/p&gt;
        ///            &lt;/div&gt;
        ///
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Recipe.File.RecipeFile_Navigation&quot;)
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;span12&quot;&gt;
        ///            &lt;h3 class=&quot;box-header&quot;&gt;About MultiPlug.Ext.Recipe.File&lt;/h3&gt;
        ///            &lt;div class=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string IsSelected(string theExtensionName1, string theExtensionName2)
        ///    {
        ///        return theExtensionName1 == theExtensionName2 ? &quot;selected&quot; : string.Empty;
        ///    }
        ///}
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span3&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string IsChecked(bool isSave)
        ///    {
        ///        return isSave ? &quot;checked&quot; : string.Empty;
        ///    }
        ///}
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align: center;&quot;&gt;Recipe via File&lt;/p&gt;
        ///            &lt;/div&gt;
        ///
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Recipe.File.RecipeFile_Navigation&quot;)
        ///
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string NavLocationIsHome()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsEditor()
        ///    {
        ///        return Model.Context.Paths.Current.StartsWith( Model.Context.Paths.Home + &quot;editor/&quot;) ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsSideload()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;sidelo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align: center;&quot;&gt;Simple File Configurator&lt;/p&gt;
        ///            &lt;/div&gt;
        ///
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Recipe.File.RecipeFile_Navigation&quot;)
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;h4&gt;Sideload&lt;/h4&gt;
        ///            &lt;div class=&quot;row-flu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sideload {
            get {
                return ResourceManager.GetString("Sideload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align: center;&quot;&gt;Simple File Configurator&lt;/p&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Recipe.File.RecipeFile_Navigation&quot;)
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;h4&gt;Sideload&lt;/h4&gt;
        ///            &lt;div class=&quot;row-fluid w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SnapShots {
            get {
                return ResourceManager.GetString("SnapShots", resourceCulture);
            }
        }
    }
}
